# ------------------------------------------------------------------------------
#                                Configuration
# ------------------------------------------------------------------------------

# Basic configuration
set -g  default-terminal   "screen-256color"
set -g  history-limit      100000
set -g  display-panes-time 2000

setw -gq utf8  on
setw -g  mouse on

set-window-option -g mode-keys vi

# Start windows and panes at 1, not 0
set  -g base-index      1
setw -g pane-base-index 1

# ------------------------------------------------------------------------------
#                                 Key bindings
# ------------------------------------------------------------------------------

# Reload configuration
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# Open new panes and windows in $PWD
bind '"' split-window -c    "#{pane_current_path}"
bind %   split-window -h -c "#{pane_current_path}"
bind c   new-window   -c    "#{pane_current_path}"

# ------------------------------------------------------------------------------
#                                   Plugins
# ------------------------------------------------------------------------------

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tpm'

set -g @continuum-save-interval '5'
set -g @continuum-restore       'on'
set -g @continuum-boot          'on'

# ------------------------------------------------------------------------------
#                                 Color scheme
# ------------------------------------------------------------------------------

# Panes
set -g pane-border-style        fg=colour238
set -g pane-active-border-style fg=colour251

set display-panes-color        colour242
set display-panes-active-color colour255


# Window status in status bar
set-option        -g window-status-current-format ' #I:#W#{?window_zoomed_flag,-Z,} '
set-window-option -g window-status-current-style  bg=colour238,fg=colour251,bold
set-option        -g window-status-separator      ''
set-option        -g window-status-format         ' #I:#W#{?window_activity_flag,!,} '
set-window-option -g window-status-style          bg=colour236,fg=colour251
 
# Status bar
set-option -g status-style        bg=colour236,fg=colour251
set        -g status-left         "#[bg=colour238,fg=colour252]"
set        -g status-right-length 64
set        -g status-right        "#[bg=colour238,fg=colour252] #T | %d %b %H:%M "
set        -g message-style       bg=colour238,fg=colour251

# Selection
set -g mode-style fg=colour251,bg=colour238

# ------------------------------------------------------------------------------
#                           Post configuration steps
# ------------------------------------------------------------------------------

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

