theme = "space-villain"
icons = "awesome"

[[block]]
block = "focused_window"
max_width = 80
show_marks = "visible"

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"

[[block]]
block = "weather"
format = "{weather} {temp}"
service = { name = "openweathermap", api_key = "ec11c7c27f0c0004caf2d9483566b18e", coordinates = ["59.937500","30.308611"], units = "metric" }

[[block]]
block = "backlight"

[[block]]
block = "sound"
step_width = 5
max_vol = 100

[[block]]
block = "battery"
driver = "upower"
format = "{percentage}"

# [[block]]
# block = "pacman"
# format = "{pacman} {aur}"
# aur_command = "checkupdates-aur"
# hide_when_uptodate = true

[[block]]
block = "apt"
format = "{count}"

